# TODO: re-enable Metric/AbcSize, Metrics/CyclomaticComplexity, and Metrics/PerceivedComplexity
AllCops:
  DisplayCopNames: true
  Exclude:
    - .bundle/*
    - bin/*
    - pkg/**/*
    - test/**/*
  SuggestExtensions: false
# Disabled useless assignment check due to Puppet type param validation
# e.g.
# validate do |value|
#   value = 'foo' if value == ''
# end
Lint/RedundantSafeNavigation:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 110
  Exclude:
    # AEM SAML endpoint does support that many parameters
    - "lib/puppet/provider/aem_saml/aem.rb"
    - "lib/puppet/type/aem_saml.rb"
    - "**/**/*_spec.rb"
Metrics/ClassLength:
  Max: 300
Metrics/LineLength:
  Max: 280
  Exclude:
    # AEM SAML endpoint does support that many parameters
    - "lib/puppet/provider/aem_saml/aem.rb"
    - "lib/puppet/type/aem_saml.rb"
Metrics/MethodLength:
  Max: 30
  Exclude:
    # AEM SAML endpoint does support that many parameters
    - "lib/puppet/provider/aem_saml/aem.rb"
    - "lib/puppet/type/aem_saml.rb"
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
# Style/BracesAroundHashParameters:
#   EnforcedStyle: context_dependent
Style/BlockDelimiters:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
